### PR TITLE
fix mod

### PR DESCRIPTION
**Pull request by deltanedas**
yw

### CODE REVIEW

**Comment by ThePythonGuy3** [comment]
OHNO

**Comment by deltanedas** [comment]
ohyes

**Comment by ThePythonGuy3** [comment]
well ig its the best u can do here

**Comment by ghost** [comment]
image

**Comment by MemFaceGo** [comment]
Nice fix

**Comment by snack-ie** [comment]
why did you close it? it fixes a bug in the mod

**Comment by antsif-a** [comment]
please merge

**Comment by summetdev** [comment]
please merge

**Comment by ThePythonGuy3** [comment]
yes pls

**Comment by deltanedas** [comment]
reopen no balls i am doing a great deed for the mindustry community

**Comment by sk7725** [comment]
ooh better sprites @MemFaceGo you definitely should

**Comment by ThatOneBepis** [comment]
Mindustry.ru and this mod are almost identical
@DeltaNedas is doing mindustry community a favor

**Comment by snack-ie** [comment]
exactly

**Comment by MemFaceGo** [comment]
-_-

**Comment by ThePythonGuy3** [comment]
ohno

**Pull request closed without merging**
